# Generated by Django 3.2.25 on 2024-03-26 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriversAllTrips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_email', models.EmailField(max_length=254)),
                ('rider_first_name', models.CharField(blank=True, max_length=255)),
                ('rider_last_name', models.CharField(blank=True, max_length=255)),
                ('rider_profile_pic', models.ImageField(upload_to='')),
                ('rider_email', models.EmailField(max_length=254)),
                ('driver_license_id', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('pickup', models.CharField(max_length=255)),
                ('dropoff', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
